MODEL:
  NUM_CLASSES: 21
  DEVICE: 'cuda:2'
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  #  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TRAIN: ("voc_2007_trainval",)
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [ 80000, 100000 ]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3
  TAN: False
  A: 0.7
  B: 0.7

OUTPUT_DIR: 'outputs/ori_sgd'